### ISSUE TITLE
Dúvida em label. 

### ISSUE THREAD

**Issue by pwebufersa** [Janiadev/pweb_2020.2_janiaOliveira#1]
Prezada, me explica de onde veio o "label for" dos inputs, pra que serve e de onde você tirou eles?

**Comment by Janiadev** [comment]
o label for foi retirado desse site https://www.w3schools.com/tags/att_label_for.asp, 
Um elemento HTML <label> representa uma legenda para um item em uma interface de usuário. Ele pode estar associado com um elemento de controle, colocando este dentro do elemento label , ou usando o atributo for . Tal controle é chamado o controle etiquetado do elemento etiqueta.

**Comment by Janiadev** [comment]
o label for foi retirado desse site
https://www.w3schools.com/tags/att_label_for.asp,
Um elemento HTML representa uma legenda para um item em uma interface de
usuário. Ele pode estar associado com um elemento de controle, colocando
este dentro do elemento label , ou usando o atributo for . Tal controle é
chamado o controle etiquetado do elemento etiqueta.

Em seg, 22 de mar de 2021 23:10, Programação WEB - UFERSA Angicos <
***@***.***> escreveu:

**Comment by pwebufersa** [comment]
Texto copiado daqui:

https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/label

Infelizmente, você não fez o exercício. Você e a pessoa que te ajudou
ficarão sem a nota dessas 2 semanas. Cuidado na próxima.

Em ter, 23 de mar de 2021 00:03, Janiadev ***@***.***>
escreveu:
